### ISSUE TITLE
Typed date is not selected on calendar

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-datepicker#170] opened 2023-11-29 21:19 UTC
## Describe the bug
When the user inputs a date through the text input (especially in the far future or far past) the calendar does NOT select the typed date. For example, when 11/20/2020 is typed in the correct format and the user opens up the calendar, it will show whatever calendar is automatically rendered by default.

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/datepicker
2. Type any date in the past (e.g. 11/20/2020)
3. Click on the input to open up calendar
4. See that nothing is selected

## Expected behavior
The typed date should correlate to a date that is selected on the calendar. In other words, if I type a date, it should select it on the calendar when the calendar is engaged.

## Screenshots
<img width="503" alt="Screenshot 2023-11-29 at 1 17 29 PM" src="https://github.com/AlaskaAirlines/auro-datepicker/assets/55998746/6c6b4d2d-1036-4013-80fa-efdcd50a2478">

## Exit Criteria

A test should be added to cover this scenario where typing a date highlights the date on the calendar.
Issue is fixed on Mobile and on Desktop

**Comment by jordanjones243** [comment] 2023-12-08 17:42
After validating this bug, the issue is not that the calendar does not select a typed date, but that the visible month/year does not change to the date that you typed. If you are viewing December 2023 and type "12/12/2023", the correct date is selected.

**Comment by blackfalcon** [comment] 2023-12-08 18:50
What @jordanjones243 has been validated. See the attached Gif for review. 

Question: @leeejune  and @braven112, was this expected as an **already defined** (not assumed) feature or is this a new feature request? 

![reported issue](https://github.com/AlaskaAirlines/auro-datepicker/assets/181089/99b7a001-7d13-4e25-bd4a-b66f89bfacd5)

**Comment by braven112** [comment] 2023-12-09 01:36
Certainly a good UI/UX fix, if not l functional bug.  Let's resize on Monday and move forward with a fix.

**Comment by jordanjones243** [comment] 2024-01-08 04:03
Ticked addressed by this PR: 
- https://github.com/AlaskaAirlines/auro-datepicker/pull/172

**Closed by jordanjones243** 2024-01-08 04:03 UTC
Labels: auro-datepicker, Type: Bug
