### ISSUE TITLE
Datepicker can be rendered outside viewport

### ISSUE THREAD

**Issue by isaiahscheel** [AlaskaAirlines/auro-datepicker#62] opened 2022-09-22 17:19 UTC
## Describe the bug

- While working on the new planbook, we have seen the datepicker be rendered above the input box and this occasionally forces the arrows and name of month to be outside of the screen

![image](https://user-images.githubusercontent.com/40191651/191810477-73e101e9-1aed-4c72-bbf1-005e009a9cc4.png)

- This is especially true for months that have a lot of rows (like 6 shown above) 

## To Reproduce

1. Go to Alaskaair.com/search
1. Make your screen small like so:
![image](https://user-images.githubusercontent.com/40191651/191810823-2598c0e2-727e-4292-969f-a894bd786c7c.png)

1. Click on date picker
1. Go to october in particular:

![image](https://user-images.githubusercontent.com/40191651/191810925-084e487a-e100-449e-bf80-244bdd88854b.png)

## Expected behavior

- Render below the input box 
- Potentially have an attribute that will force to render below the input box always 

## Screenshots

- Attached above

## Desktop (please complete the following information):

 - OS: macOS
 - Browser chrome
 - Version n/a

## Additional context

- Reported first by a designer but numerous times sense from testers

**Comment by blackfalcon** [comment] 2022-09-22 18:30
This 'feature' is coming from the auro-dropdown menu which uses popper.js. By default popper moves the placement of the bib to above or below based on the scroll. 

The consideration here is always to have it appear below the trigger option. 

@jason-capsule42 thoughts?

**Comment by shonore-aa** [comment] 2022-09-26 17:35
I am on the latest version of auro-datepicker and auro-dropdown and I am not able to recreate this issue locally.

**Comment by shonore-aa** [comment] 2022-09-26 17:36
I am able to recreate the issue once I deploy to our TEST, QA, or PROD environment

**Comment by jason-capsule42** [comment] 2022-09-29 04:52
I don't see this as a bug. 

While Popper.js is trying to fit the dropdown bib inside the viewport, the issue here is that the calendar will have a variable number of rows for the date grid depending on the month. In the example in the screenshot, we see the largest possible calendar. This will simply not fit in the viewport. Our calendar and in turn datepicker are not designed to fit on a short screen.

**Comment by blackfalcon** [comment] 2022-09-29 16:47
@jason-capsule42 I agree that this is not a bug. The UI is working as expected. But, that being said, if we fix the dropdown bib for datepicker to always be at the bottom, then the page would scroll when there is more room needed to render the calendar. 

With the current configuration, is there a way to use that option or would we need to add that as a feature?

**Comment by blackfalcon** [comment] 2022-10-12 18:21
@jason-capsule42 @diana-dipalma @shonore-aa @leeejune 

This issue was brought up again in today's standup. This issue is not closed, but is being reassigned for engineering and design refinement so that work can be prioritized. 

As stated, the current version is working as expected, so the conversation is more about enhancing the datepicker experience so that is better suited for a mobile experience. Options that were discussed include, but are not limited to the following: 

1. a full screen modal experience when the calendar is presented on a mobile device
2. a reduced in size calendar experience to better fit the limited space of a mobile device
3. forcing the calendar to always appear BELOW the trigger

**Comment by blackfalcon** [comment] 2022-10-17 21:10
@leeejune will speak to the designer revenue team to get feedback on ours and the search team's concerns about the UX of this element. 

Post this discussion, this issue will be revised. We expect new design work to be an option and from that design work new feature work will be discussed. 

This issue will be closed when those new feature issues are created.

**Comment by leeejune** [comment] 2022-10-18 07:31
Mobile calendar design exists in the "Future Release" page in Figma. 

https://www.figma.com/file/mZzZNE0cEPnphZozbaZfDy/Calendar?node-id=1839%3A23842

**Comment by leeejune** [comment] 2022-10-18 18:31
@blackfalcon There is a "one way" design here: https://www.figma.com/file/mZzZNE0cEPnphZozbaZfDy/Calendar?node-id=1839%3A23843

![Screen Shot 2022-10-18 at 11 30 36 AM](https://user-images.githubusercontent.com/55998746/196514624-5460a8d0-3864-4033-9394-0315438fc183.png)

Are you referring to the top portion as the "special calendar header"?

**Comment by blackfalcon** [comment] 2022-10-18 20:55
The crux of this issue is that auro-datepicker, operating as expected, moves above or below the triggering element based on where the most room is in the browser window.

The proposed solution is to add a `fixed` attribute to the date picker that will force the element to always open down.

The following issues have been created to address the positioning of the bib when the trigger element is selected. . 

- https://github.com/AlaskaAirlines/auro-datepicker/issues/77
- https://github.com/AlaskaAirlines/auro-dropdown/issues/169

**Comment by blackfalcon** [comment] 2022-10-18 20:56
I am moving this issue into `refinement` due to the current fluidity of the issue. The 1st goal is to apply the `fixed` attribute, then we will come back and scope out the work discussed related to a correct mobile experience.

**Comment by braven112** [comment] 2022-10-19 21:38
The designs for this have the calendar always being the same height regardless of the number of rows.  We'll attempt to fix that and verify that will fix this issue.

**Closed** 2022-10-20 17:38 UTC
Labels: auro-datepicker, Type: Design
