### ISSUE TITLE
valueSet does not trigger correctly in FF and Safari

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-datepicker#64] opened 2022-09-23 19:13 UTC
## Describe the bug

valueSet does not trigger upon calendar selection on Firefox and Safari.

## To Reproduce

1. Go to ['this page'](https://auro.alaskaair.com/components/auro/datepicker/api)
2. Scroll down to the `valueSet` event example at the bottom
3. Select a date via the calendar

## Expected behavior

valueSet does trigger upon calendar selection in all browsers

## Desktop (please complete the following information):

 - Browser: Firefox, Safari

**Comment by jason-capsule42** [comment] 2022-09-29 04:31
Unable to reproduce this issue. I suspect this was an implementation issue.

**Comment by blackfalcon** [comment] 2022-10-13 17:18
@jordanjones243 please investigate this issue where the demo is not providing the expected output. Also, please update the demo to alert the reader as what to look for in a successful scenario.

**Comment by jordanjones243** [comment] 2022-10-18 19:00
I have updated the issue description to better explain the error conveyed initially. Although, I was unable to reproduce the error where the valueSet example is not being triggered properly and will therefore close this ticket.

**Comment by jordanjones243** [comment] 2022-10-18 19:00
> @jason-capsule42 I am not even sure what this demo is supposed to be illustrating. The instructions are not really all that clear. I see in the code example there is an expectation of a `console.warn`, but when I open the console and select a date, the only thing that show up right now is an error from input?
> 
> Is this a bug with the implementation or the demo?
> 
> <img alt="Screen Shot 2022-09-29 at 7 46 04 AM" width="1526" src="https://user-images.githubusercontent.com/181089/193063603-d5827dee-4d92-4774-8f2b-c72715459433.png">

This ticket will be further investigated and a new ticket will be opened if it is deemed a necessary error that can be fixed.

**Closed by jordanjones243** 2022-10-18 19:00 UTC
Labels: auro-datepicker, not-reviewed, Type: Bug, unable to repro
