### ISSUE TITLE
Never Fires an API Request For Chevron Icons In Firefox

### ISSUE THREAD

**Issue by tjhooper1** [AlaskaAirlines/auro-datepicker#84] opened 2022-10-25 17:25 UTC
## Describe the bug

I noticed when implementing the Auro Datepicker that Firefox just show blue boxes for the chevron icons. Opening the network tab reveals an API request for those icons don't fire like they do in Chrome.
## To Reproduce

- Open Chrome and click into the date picker calendar. Inspect the network tab to see requests being made for the chevron icons

## Expected behavior

Chevron icons display in the calendar no matter the browser
## Desktop (please complete the following information):
![Screen Shot 2022-10-25 at 1 21 43 PM](https://user-images.githubusercontent.com/28743134/197841341-6b65f39f-dd75-4d64-90be-b54c72d38e54.png)
![Screen Shot 2022-10-25 at 1 22 14 PM](https://user-images.githubusercontent.com/28743134/197841350-e65d089c-d6fe-4a30-92de-8b49ce14a19b.png)

## Additional context

N/A

**Comment by blackfalcon** [comment] 2022-10-25 18:28
@tjhooper1 I am unable to repro this issue with the Auro docsite. Are you able to repro this issue? 

Are you using the latest version of the element in your project? 

When you installed the element, have you addressed all the [peer dependencies](https://github.com/AlaskaAirlines/auro-datepicker#peer-dependencies)?

<img width="775" alt="Screen Shot 2022-10-25 at 11 26 29 AM" src="https://user-images.githubusercontent.com/181089/197852512-5f26462e-10f5-4d53-a9b7-c0d6f14d07a0.png">

**Comment by tjgrist** [comment] 2022-10-25 19:52
@blackfalcon I am able to repro this on Firefox, but not safari. Firefox:
<img width="596" alt="Screen Shot 2022-10-25 at 12 52 09 PM" src="https://user-images.githubusercontent.com/17755678/197868862-b847aa87-f967-4197-b5b9-330b0075f2ec.png">

**Comment by tjhooper1** [comment] 2022-10-25 19:59
> @tjhooper1 I am unable to repro this issue with the Auro docsite. Are you able to repro this issue?
> 
> Are you using the latest version of the element in your project?
> 
> When you installed the element, have you addressed all the [peer dependencies](https://github.com/AlaskaAirlines/auro-datepicker#peer-dependencies)?
> 
> <img alt="Screen Shot 2022-10-25 at 11 26 29 AM" width="775" src="https://user-images.githubusercontent.com/181089/197852512-5f26462e-10f5-4d53-a9b7-c0d6f14d07a0.png">

I actually checked Safari again and see the chevrons download. That's my mistake, I thought I saw the issue there too. I mainly tested on Firefox. I'll update the PR accordingly.

As far as the other question about peer dependencies, here's the latest we have in the flightchanges microsite.

```json
    "@alaskaairux/webcorestylesheets": "^3.7.3",
    "@aurodesignsystem/auro-alert": "^2.0.1",
    "@aurodesignsystem/auro-calendar": "^1.0.4",
    "@aurodesignsystem/auro-datepicker": "^1.2.3",
    "@aurodesignsystem/auro-dropdown": "^2.9.0",
    "@aurodesignsystem/auro-hyperlink": "^3.1.0",
    "@aurodesignsystem/auro-input": "^2.9.1",
    "@aurodesignsystem/auro-menu": "^3.3.1",
    "@aurodesignsystem/auro-select": "^2.2.0",
    "@aurodesignsystem/auro-skeleton": "^2.0.1",

**Comment by blackfalcon** [comment] 2022-10-26 21:15
@tjhooper1 sooo... there is no longer an issue and we can close this?

**Comment by tjhooper1** [comment] 2022-10-26 21:18
> 

I believe there still is an issue for Firefox only. I've attached a screen shot from the change reservation page on the testres01 server on Firefox
<img width="1099" alt="Screen Shot 2022-10-26 at 5 17 06 PM" src="https://user-images.githubusercontent.com/28743134/198140182-1c6737e4-b3bf-4bcf-8396-d2c011cfca23.png">

**Comment by tjgrist** [comment] 2022-10-26 21:19
@blackfalcon Check the auro docs site for datepicker on firefox. Chevrons are not displaying.

**Comment by blackfalcon** [comment] 2022-10-27 22:45
@jason-capsule42 do you have any idea on why this is not working with Firefox?

**Comment by blackfalcon** [comment] 2022-12-14 18:22
In refinement, this issue is reproducible. Should be assigned to dev in any sprint for review and correction. 

### Exit criteria 

No blue boxes in Firefox, but should show proper icons.

**Comment by jordanjones243** [comment] 2023-01-24 22:53
This issue seems to be coming from `auro-calendar`. In order to display the icons via CSS, we use the `webkit-mask-box-image` property. While this is supported in other browsers like Safari and Chrome, this is not supported in Firefox. I am currently running into the same exact issue in `auro-nav`. Furthermore, Mozilla declares that CSS properties starting with the `webkit` prefix are not standard use, which means we need to find a better solution to support the use of icons via CSS within all browsers.

**Comment by jordanjones243** [comment] 2023-01-24 22:57
Here is the code that I am referring to from `style.scss` in `auro-calendar` in the comment above: 
![Screen Shot 2023-01-24 at 2 56 31 PM](https://user-images.githubusercontent.com/55807669/214439687-a9bda6da-ce4a-4cbc-a8aa-22d87260c683.png)

**Comment by jordanjones243** [comment] 2023-01-24 23:05
A potential solution is that we could use both `-webkit-mask-box-image` (used for Firefox support) AND `mask-image` (used for Safari support) simultaneously. I have tested this and the UI appeared normally across Chrome, Firefox, Safari and Edge.

What are your thoughts @blackfalcon @jason-capsule42?

**Comment by jordanjones243** [comment] 2023-01-24 23:14
Please now reference this issue for further work: 
- https://github.com/AlaskaAirlines/auro-calendar/issues/37

**Comment by blackfalcon** [comment] 2023-01-24 23:15
> A potential solution is that we could use both `-webkit-mask-box-image` (Chrome, Edge, Safari) AND `mask-image` (Firefox) simultaneously. 

Correction in statement. 

Yes. we can do that. There is nothing wrong with stacking vendor-prefixed CSS properties.

**Closed by jordanjones243** 2023-01-24 23:14 UTC
Labels: auro-datepicker, Type: Bug

**Comment by jason-capsule42** [comment] 2023-01-25 02:38
Agree with Dale. We can use all the vendor prefixes we want.
